// A partial list of Tailwind CSS classes for the autocomplete feature.
// A full list can be very large; this provides a representative sample.
export const tailwindClasses: string[] = [
  'p-0', 'p-1', 'p-2', 'p-3', 'p-4', 'p-5', 'p-6', 'p-8', 'p-10', 'p-12',
  'px-0', 'px-1', 'px-2', 'px-3', 'px-4', 'px-5', 'px-6', 'px-8', 'px-10', 'px-12',
  'py-0', 'py-1', 'py-2', 'py-3', 'py-4', 'py-5', 'py-6', 'py-8', 'py-10', 'py-12',
  'pt-0', 'pt-1', 'pt-2', 'pt-3', 'pt-4', 'pt-5', 'pt-6',
  'pr-0', 'pr-1', 'pr-2', 'pr-3', 'pr-4', 'pr-5', 'pr-6',
  'pb-0', 'pb-1', 'pb-2', 'pb-3', 'pb-4', 'pb-5', 'pb-6',
  'pl-0', 'pl-1', 'pl-2', 'pl-3', 'pl-4', 'pl-5', 'pl-6',
  'm-0', 'm-1', 'm-2', 'm-3', 'm-4', 'm-5', 'm-6', 'm-auto',
  'mx-0', 'mx-1', 'mx-2', 'mx-3', 'mx-4', 'mx-5', 'mx-6', 'mx-auto',
  'my-0', 'my-1', 'my-2', 'my-3', 'my-4', 'my-5', 'my-6', 'my-auto',
  'mt-0', 'mt-1', 'mt-2', 'mt-3', 'mt-4', 'mt-5', 'mt-6',
  'mr-0', 'mr-1', 'mr-2', 'mr-3', 'mr-4', 'mr-5', 'mr-6',
  'mb-0', 'mb-1', 'mb-2', 'mb-3', 'mb-4', 'mb-5', 'mb-6',
  'ml-0', 'ml-1', 'ml-2', 'ml-3', 'ml-4', 'ml-5', 'ml-6',
  'space-x-0', 'space-x-1', 'space-x-2', 'space-x-4',
  'space-y-0', 'space-y-1', 'space-y-2', 'space-y-4',
  'w-0', 'w-1', 'w-2', 'w-4', 'w-full', 'w-screen', 'w-auto', 'w-1/2', 'w-1/3', 'w-2/3', 'w-1/4',
  'h-0', 'h-1', 'h-2', 'h-4', 'h-full', 'h-screen', 'h-auto',
  'min-w-0', 'min-w-full',
  'min-h-0', 'min-h-full', 'min-h-screen',
  'max-w-0', 'max-w-none', 'max-w-xs', 'max-w-sm', 'max-w-md', 'max-w-lg', 'max-w-xl',
  'max-h-0', 'max-h-full', 'max-h-screen',
  'flex', 'inline-flex', 'grid', 'inline-grid', 'block', 'inline-block', 'hidden',
  'flex-row', 'flex-row-reverse', 'flex-col', 'flex-col-reverse',
  'flex-wrap', 'flex-wrap-reverse', 'flex-nowrap',
  'flex-1', 'flex-auto', 'flex-initial', 'flex-none',
  'items-start', 'items-end', 'items-center', 'items-baseline', 'items-stretch',
  'justify-start', 'justify-end', 'justify-center', 'justify-between', 'justify-around', 'justify-evenly',
  'gap-0', 'gap-1', 'gap-2', 'gap-4', 'gap-x-0', 'gap-x-1', 'gap-y-0', 'gap-y-1',
  'grid-cols-1', 'grid-cols-2', 'grid-cols-3', 'grid-cols-4', 'grid-cols-5', 'grid-cols-6',
  'grid-rows-1', 'grid-rows-2', 'grid-rows-3',
  'col-span-1', 'col-span-2', 'col-span-full',
  'row-span-1', 'row-span-2',
  'absolute', 'relative', 'fixed', 'sticky', 'static',
  'top-0', 'right-0', 'bottom-0', 'left-0',
  'inset-0', 'inset-x-0', 'inset-y-0',
  'z-0', 'z-10', 'z-20', 'z-30', 'z-40', 'z-50', 'z-auto',
  'bg-transparent', 'bg-black', 'bg-white', 'bg-gray-500', 'bg-red-500', 'bg-yellow-500', 'bg-green-500', 'bg-blue-500', 'bg-indigo-500', 'bg-purple-500', 'bg-pink-500',
  'bg-juki-dark', 'bg-juki-dark-2', 'bg-juki-dark-3', 'bg-juki-green', 'bg-juki-light',
  'text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl', 'text-2xl', 'text-3xl', 'text-4xl', 'text-5xl',
  'font-thin', 'font-extralight', 'font-light', 'font-normal', 'font-medium', 'font-semibold', 'font-bold', 'font-extrabold', 'font-black',
  'text-left', 'text-center', 'text-right', 'text-justify',
  'text-transparent', 'text-black', 'text-white', 'text-gray-500', 'text-red-500', 'text-yellow-500', 'text-green-500', 'text-blue-500',
  'border', 'border-0', 'border-2', 'border-4', 'border-8',
  'border-solid', 'border-dashed', 'border-dotted', 'border-double', 'border-none',
  'border-gray-500', 'border-red-500', 'border-juki-green',
  'rounded-none', 'rounded-sm', 'rounded', 'rounded-md', 'rounded-lg', 'rounded-xl', 'rounded-2xl', 'rounded-3xl', 'rounded-full',
  'rounded-t-lg', 'rounded-r-lg', 'rounded-b-lg', 'rounded-l-lg',
  'shadow-sm', 'shadow', 'shadow-md', 'shadow-lg', 'shadow-xl', 'shadow-2xl', 'shadow-inner', 'shadow-none',
  'opacity-0', 'opacity-25', 'opacity-50', 'opacity-75', 'opacity-100',
  'cursor-pointer', 'cursor-wait', 'cursor-not-allowed',
  'transition', 'transition-all', 'transition-colors', 'transition-opacity', 'transition-shadow', 'transition-transform',
  'duration-75', 'duration-100', 'duration-150', 'duration-200', 'duration-300', 'duration-500', 'duration-700', 'duration-1000',
  'ease-linear', 'ease-in', 'ease-out', 'ease-in-out',
  'transform', 'scale-50', 'scale-100', 'scale-125',
  'rotate-45', 'rotate-90', 'rotate-180',
  'translate-x-1', 'translate-x-full', '-translate-x-1/2',
  'translate-y-1', 'translate-y-full', '-translate-y-1/2',
  'hover:bg-blue-700', 'hover:text-white', 'hover:opacity-75', 'hover:shadow-lg', 'hover:scale-110',
  'focus:outline-none', 'focus:ring', 'focus:ring-juki-green', 'focus:border-blue-500',
  'disabled:opacity-50', 'disabled:cursor-not-allowed',
  'truncate', 'text-ellipsis', 'text-clip',
  'overflow-auto', 'overflow-hidden', 'overflow-visible', 'overflow-scroll',
  'object-contain', 'object-cover', 'object-fill', 'object-none', 'object-scale-down',
  'sr-only',
];
